declare const _default: {
    Query: {
        order: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
    };
    Mutation: {
        orderAddDish: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
        orderReplaceDish: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
        orderRemoveDish: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
        orderSetDishAmount: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
        orderSetDishComment: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
        orderUpdate: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
        orderClone: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
        orderPromocodeApply: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
        orderPromocodeReset: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string;
                shortId?: string;
                state?: string;
                concept?: string[];
                isMixedConcept?: boolean;
                dishes?: import("@webresto/core").OrderDishRecord[] | number[];
                paymentMethod?: import("@webresto/core").PaymentMethodRecord | string;
                paymentMethodTitle?: string;
                paid?: boolean;
                isPaymentPromise?: boolean;
                promotionState?: import("@webresto/core").PromotionState[];
                promotionErrors?: object | object[];
                promotionCode?: import("@webresto/core/models/PromotionCode").PromotionCodeRecord | string;
                promotionCodeDescription?: string;
                promotionCodeString?: string;
                promotionFlatDiscount?: number;
                promotionDelivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery;
                promotionCodeCheckValidTill?: string;
                promotionUnorderable?: boolean;
                isPromoting?: boolean;
                dishesCount?: number;
                uniqueDishes?: number;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default;
                address?: import("@webresto/core/interfaces/Address").default;
                comment?: string;
                personsCount?: string;
                date?: string;
                problem?: boolean;
                rmsDelivered?: boolean;
                rmsId?: string;
                rmsOrderNumber?: string;
                rmsOrderData?: any;
                rmsDeliveryDate?: string;
                rmsErrorMessage?: string;
                rmsErrorCode?: string;
                rmsStatusCode?: string;
                rmsOrderStatus?: string;
                pickupPoint?: import("@webresto/core").PlaceRecord | string;
                selfService?: boolean;
                delivery?: import("@webresto/core/adapters/delivery/DeliveryAdapter").Delivery | null;
                deliveryDescription?: string;
                message?: string;
                deliveryItem?: import("@webresto/core").DishRecord | string;
                deliveryCost?: number;
                totalWeight?: number;
                trifleFrom?: number;
                bonusesTotal?: number;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus;
                total?: number;
                basketTotal?: number;
                orderTotal?: number;
                discountTotal?: number;
                orderDate?: string;
                tag?: string;
                deviceId?: string;
                nonce?: number;
                hash?: string;
                user?: import("@webresto/core").UserRecord | string;
                customData?: any;
            }>;
        };
    };
};
export default _default;
