import { ResolvedCaptcha } from "@webresto/core/adapters";
import { OrderRecord } from "@webresto/core";
type PromotionCodeResponse = {
    order: OrderRecord;
    promocodeValid: boolean | null;
    promotionCodeString: string | null;
    promotionCodeDescription: string | null;
    message: {
        title: string;
        type: "success" | "error" | "info";
        message: string;
    };
};
type PromotionCodeApplyPayload = {
    orderId: string;
    promocode: string;
    captcha: ResolvedCaptcha;
};
declare const _default: {
    Query: {
        orders: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }[]>;
        };
        order: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }>;
        };
    };
    Mutation: {
        orderAddDish: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }>;
        };
        orderReplaceDish: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }>;
        };
        orderRemoveDish: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }>;
        };
        orderSetDishAmount: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }>;
        };
        orderSetDishComment: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }>;
        };
        orderUpdate: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }>;
        };
        orderClone: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<{
                createdAt?: Date | undefined;
                updatedAt?: Date | undefined;
                id?: string | undefined;
                shortId?: string | undefined;
                orderedAt?: number | undefined;
                completedAt?: number | undefined;
                state?: string | undefined;
                concept?: string[] | undefined;
                isMixedConcept?: boolean | undefined;
                dishes?: number[] | import("@webresto/core").OrderDishRecord[] | undefined;
                paymentMethod?: string | import("@webresto/core").PaymentMethodRecord | undefined;
                paymentMethodTitle?: string | undefined;
                paid?: boolean | undefined;
                isPaymentPromise?: boolean | undefined;
                promotionState?: import("@webresto/core").PromotionState[] | undefined;
                promotionErrors?: object | object[] | undefined;
                promotionCode?: string | import("@webresto/core/models/PromotionCode").PromotionCodeRecord | undefined;
                promotionCodeDescription?: string | undefined;
                promotionCodeString?: string | undefined;
                promotionFlatDiscount?: number | undefined;
                promotionDelivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | undefined;
                promotionCodeCheckValidTill?: string | undefined;
                promotionUnorderable?: boolean | undefined;
                isPromoting?: boolean | undefined;
                dishesCount?: number | undefined;
                uniqueDishes?: number | undefined;
                modifiers?: any;
                customer?: import("@webresto/core/interfaces/Customer").default | undefined;
                address?: import("@webresto/core/interfaces/OrderAddress").default | undefined;
                comment?: string | undefined;
                personsCount?: string | undefined;
                date?: string | undefined;
                problem?: boolean | undefined;
                rmsDelivered?: boolean | undefined;
                rmsId?: string | undefined;
                rmsOrderNumber?: string | undefined;
                rmsOrderData?: any;
                rmsDeliveryDate?: string | undefined;
                rmsErrorMessage?: string | undefined;
                rmsErrorCode?: string | undefined;
                rmsStatusCode?: string | undefined;
                rmsOrderStatus?: string | undefined;
                pickupPoint?: string | import("@webresto/core").PlaceRecord | undefined;
                cookingPoints?: string[] | undefined;
                maxWaitMinutes?: number | undefined;
                serviceType?: "delivery" | "dine-in" | "pickup" | undefined;
                delivery?: import("@webresto/core/adapters/delivery/contracts").Delivery | null | undefined;
                message?: string | undefined;
                totalWeight?: number | undefined;
                trifleFrom?: number | undefined;
                bonusesTotal?: number | undefined;
                spendBonus?: import("@webresto/core/interfaces/SpendBonus").SpendBonus | undefined;
                total?: number | undefined;
                basketTotal?: number | undefined;
                discountTotal?: number | undefined;
                orderDate?: string | undefined;
                tag?: string | undefined;
                deviceId?: string | undefined;
                orderedOnPlatform?: string | undefined;
                nonce?: number | undefined;
                hash?: string | undefined;
                user?: string | import("@webresto/core").UserRecord | undefined;
                customData?: any;
                logs?: import("@webresto/core").OrderLogEntry[] | undefined;
            }>;
        };
        orderPromocodeApply: {
            def: string;
            fn: (parent: any, args: PromotionCodeApplyPayload, context: any) => Promise<PromotionCodeResponse>;
        };
        orderPromocodeReset: {
            def: string;
            fn: (parent: any, args: any, context: any) => Promise<PromotionCodeResponse>;
        };
    };
};
export default _default;
export declare function getNewCart(context?: any, orderId?: string): Promise<any>;
